--1 what is the total revenue generated by gender 

select gender, sum(purchase_amount) as revenue
from customer
group by gender 

--2 which customer used a discount code but still spent more than the average purchase amount

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes'
and purchase_amount >= (select avg(purchase_amount) from customer)


--3 which are the top 5 products with the highest average review rating 

select item_purchased, round(avg(review_rating::numeric),2) as average_product_rating
from customer
group by item_purchased
order by avg(review_rating) desc 
limit 5

--4 compare the average purchase amounts between standard and express shipping 
select shipping_type, round(avg(purchase_amount),2) as avg_amount
from customer
where shipping_type in ('Standard' ,'Express')
group by shipping_type


--5 Do subscribed customers spent more? Compare average spend and total revenue between subscribers and non-subscribers
select subscription_status, sum(purchase_amount) as revenue, 
round(avg(purchase_amount),2) as avg_spent, count(customer_id) as total_customer
from customer
group by subscription_status

--6 which 5 products have the highest percentage of purchases with the discount applied
select item_purchased, 
round(100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc 
limit 5

--7 Segment customers into new, returning and loyal based on their
-- total number of purchases and show the count of each segment 
with cte as(
select customer_id,previous_purchases,
case when previous_purchases = 1 then 'New'
	 when previous_purchases between 2 and 10 then 'Returning'
	 else 'Loyal' end as customer_segment

from customer
)
select customer_segment, count(*) as total_customer
from cte
group by customer_segment


--8 what are the top 3 most purchased products within each category
with cte as (
select category, item_purchased, count(customer_id) as total_customers,
row_number()over(partition by category order by count(customer_id)desc ) as item_rank
from customer
group by category, item_purchased
)
select category, item_purchased,item_rank, total_customers
from cte 
where item_rank <=3

--9 Are customers who are repeat buyers(more than 5 previous purcases) are also likely to subscribe ?

select subscription_status, count(customer_id) as total_cnt 
from customer
where previous_purchases > 5
group by subscription_status

--10 what is the revenue contribution of each age group 

select age_group, sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc 



